### ISSUE TITLE
write documentation on user account and plans

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-frontend#1241]
### Users need to understand:
- how to open an account
- which type of data they can access under which plans
- reminder of the terms of use (link)
- ....

### Todos
We work in this [folder](https://drive.google.com/drive/u/0/folders/1k5-_bxWc_uKuyvR-Hm_FzGcIKdT3v8DS).
- [ ] ME add previous pieces from former version of ToU
- [ ] MD and DG to complete and review
- [ ] Reviews by colleagues to check completeness and clarity
- [ ] Online update (DG), only when new data is there.

**Comment by e-maud** [comment]
## Status update:

### User plans documentation

- [ ] The user plan table of reference is in this [Impresso User Plans](https://docs.google.com/spreadsheets/d/1ibatzAED9Xl9oY4hpjOruQDOPNXfCWV90dGzFueo2ss/edit?gid=0#gid=0) spreadsheet, which is already quite clear for users.
- [ ] It has been integrated in the [datalab web page](https://impresso-project.ch/datalab/plans/).
- [ ] A few adjustment remain to be done, described here: https://github.com/impresso/impresso-datalab/issues/79

### Corpus overview

- [ ] A corpus overview has been generated ([file](https://github.com/impresso/impresso-corpus-metadata/tree/master/data/access_rights_masterfiles), [issue](https://github.com/impresso/impresso-corpus-metadata/issues/45)
- [ ] And integrated on the [datalab website](https://impresso-project.ch/datalab/corpus-overview/)
- [ ] A few adjustments remain to be done and will be described in another issue (todo)

### FAQ additions
- to check if necessary
