### ISSUE TITLE
Todolist UX for February Milestone

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#184]
February deadline

**search**
- [ ] Quirky filters. Add a line to specify what is about
- [x] Add search pills
- [x] Add collections in article
- [ ] Add save query button
- [x] Add export query button

**Reading**
- [x] table of contents: add scroll to selected article
- [x] Article page fix table of contents
- [x] Click on region lead you to the article page
- [x] Add collections at article page level
- [x] Get rid of overview and use the table of contents to be restyled

**Collect**
- [ ] Test collection for newbie user
- [x] Test collection page and collection creation with Estelle
- [x] Delete a collection @danieleguido but brepare the UI

**Explore**
- [ ] Newspaper page
- [ ] Topics page
- [ ] Connects filters and article newspaper titles with the related detail page

Feedback
- [x] Tawkto status?

**Comment by tvanbeek** [comment]
collection page
- number of articles in collection in sidebar displays 0
- remove "manage collection" button in the "add to collection" submenu

newspaper titles page
- not so useful yet, it misses details and sort/filter of issues

topics
- slideout the words
- visual is not usefull

**Comment by Bunoute** [comment]
- EB writes the explanation for TM page

**Comment by Bunoute** [comment]
Suggestion for the newspaper titles page: maybe display the most recent front pages instead of the oldest?

**Comment by Bunoute** [comment]
Suggestion for the visualisation of the bag of words for the TM: expand, show first only 10 (or more) words?

**Comment by Bunoute** [comment]
another suggestion: would it be possible to make the table of content collapsable/expandable? it takes a lot of space on the screen and makes it hard to read the article, especially when the text is juxtaposed to the image.

**Comment by mduering** [comment]
Go to search page after loading https://impresso-project.ch/dev/

**Comment by mduering** [comment]
Strange things happen when selecting newspapers from the list:
	API Error : See Console for details.
	Newspapers disappear from list
	GDL appears multiple times

**Comment by mduering** [comment]
After adding a title it does not update the count in collections, it does not appear in dashboard or collections.
After clicking “Test” they appear, count still 0

 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/4408050/52935505-e6df2380-3359-11e9-8368-7dc74add3254.png">

**Comment by mduering** [comment]
Does it make sense to grey out Dashboard for the alpha?

**Comment by mduering** [comment]
Newspaper page: “Show all first pages” no priority, display metadata instead

**Comment by mduering** [comment]
Topic model view: display articles

**Comment by mduering** [comment]
Not urgent

Select all in Tile mode: “1 item selected” instead of 12

Can’t add titles to collection when in tile mode

Grey out alternative interface languages


Account
	Dashboard
	“C”ollections


Topic model viewer: when I change “Size by” from Degree to “highest word probability” design changes, menus get shuffled around


Idea: would it not make more sense to use the graph only for the exploration of a topic model’s neighbours? The complete graph is hard to make sense of, but with a given topic models we can learn which other topic models are similar and should be considered as well.

**Comment by Bunoute** [comment]
in COLLECTIONS >> Delete
when I delete a collection, it deletes its contents, not the collection itself...
maybe add a button: delete all articles from collection
to differentiate from deleting the collection?

**Comment by mduering** [comment]
longer topic models cause the close icon to disappear in search page

<img width="430" alt="image" src="https://user-images.githubusercontent.com/4408050/53164380-58c0a280-35d0-11e9-811e-1ffcb164471e.png">

**Comment by mduering** [comment]
Topci model page

Sorting does not seem to work

**Comment by mduering** [comment]
article highlights don't work all the time (well known already I think but for completion). Perhaps related, screenshot 2 shows TEXT view: should text and snippet on the right align?

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/4408050/53178027-60dd0a00-35f1-11e9-8248-24553865b9d2.png">

**Comment by mduering** [comment]
@PaulSchroeder I just noticed that the collection dialogue does not close automatically after I add an article, the overlay continues to follow when I scroll down

**Comment by mduering** [comment]
Timeline until 2158?
<img width="371" alt="image" src="https://user-images.githubusercontent.com/4408050/53411771-b174ae80-39c7-11e9-9c93-06025b493f98.png">

**Comment by mduering** [comment]
can't remove selected facets (assume wip..)

**Comment by mduering** [comment]
overlays broken? https://impresso-project.ch/dev/#/issue/LCG-1849-09-08-a/page/LCG-1849-09-08-a-p0002

**Comment by mduering** [comment]
https://impresso-project.ch/dev/#/issue/LCG-1849-09-08-a/page/LCG-1849-09-08-a-p0003 

<img width="972" alt="image" src="https://user-images.githubusercontent.com/4408050/53412177-f220f780-39c8-11e9-8c33-449d33e624ea.png">

**Comment by mduering** [comment]
Newspapers page

https://impresso-project.ch/dev/#/newspapers/JDF/metadata

link is broken:

provenanceUri | → http://permalink.snl.ch/bib/sz001912352
-- | --

**Comment by mduering** [comment]
Newspapers page

Click on second or last page in list of newspapers
<img width="115" alt="image" src="https://user-images.githubusercontent.com/4408050/53413075-58a71500-39cb-11e9-8a49-0edeb8638bd7.png">

leads to 

<img width="873" alt="image" src="https://user-images.githubusercontent.com/4408050/53413104-6bb9e500-39cb-11e9-868b-0c2d0152c55e.png">


click on "Newspaper Titles" does not change anything, only page reload fixes it

**Comment by mduering** [comment]
Newspaper Titles

Order by does not work - deactivate for alpha?

**Comment by mduering** [comment]
remove the "tabloid" login

**Comment by Bunoute** [comment]
- in search page: removing collection pill on article : does not always work 
- in search page: when doing the bulk selection, could the selection be removed once the articles have been added to the collection?
- in search page: the topic do not have names ;)
- in collection page: "update collection" does not work (API error...)
- in collection page: when removing a collection label, the article stays (unless we exit the collection and return to that collection)
- on the newspaper page: very nice visualisation! could it be possible to add the newspaper title and not only the dates (or make it always visible, not only when we hover over...)?
- could it be possible to differentiate what is there from what is not yet available?
(sorry if all these bugs are already known :) )

**Comment by Bunoute** [comment]
in reading view: on the article page, in text mode, the add to collection button works but is not entirely visible (wasn't it the plan to postpone the marginalia in general for after alpha?)

**Comment by Bunoute** [comment]
in search page, there does not seem to be a difference whether I use fuzzy/exact etc. search options, is that already in place?

**Comment by e-maud** [comment]
Newspaper pages: when looking at 'list of 1st pages', it seems that always the same are returned, i.e. the ones of L'impartial.

**Comment by Bunoute** [comment]
In the search page: it is not possible to select more than one newspaper title at the time?

**Comment by Bunoute** [comment]
the end date in the search summary does not depend on the selected newspaper title (always 1.1.2018)

![image](https://user-images.githubusercontent.com/32094266/53547833-5ca07780-3b30-11e9-95d4-eccb2566a5b3.png)

**Comment by Bunoute** [comment]
trying out the EN language articles, cannot apply this filter...

**Comment by Bunoute** [comment]
on collection page: delete a collection does not work

**Comment by danieleguido** [comment]
> the end date in the search summary does not depend on the selected newspaper title 
(always 1.1.2018)

@Bunoute it is a known bug indeed. The issue here is that a filter by date range is automatically sent without the user knowing about it (with the maximum daterange, in this case from 1780 to 2018).
This has a big impact on performance, too. We're going to fix this for the following release.

**Comment by danieleguido** [comment]
@maud thanks, fixed in the latest release:
- [x] when looking at 'list of 1st pages', it seems that always the same are returned, i.e. the ones of L'impartial.
- [x] order by "date ascending/descending" does not work properly (it seems)

**Comment by Bunoute** [comment]
Sorry for the new comment, it's just to integrate a screenshot.
The snippets seem to be displayed twice:
![image](https://user-images.githubusercontent.com/32094266/53581291-95b30900-3b7d-11e9-872d-f0bb0502357f.png)

**Comment by Bunoute** [comment]
and here the visual illustration of the query box comment: 
reminder: 
* when I try to edit my query:
![image](https://user-images.githubusercontent.com/32094266/53581846-a2842c80-3b7e-11e9-9edc-85ed70427c45.png)


 it just closes the box
![image](https://user-images.githubusercontent.com/32094266/53581826-9ac48800-3b7e-11e9-86ff-7efe73a08b34.png)


 I have to reopen it to edit
![image](https://user-images.githubusercontent.com/32094266/53581809-94361080-3b7e-11e9-858d-deb5c95a73f3.png)

**Comment by mromanello** [comment]
- In topic model viewer: when I change the order by in the topic display (highest first vs lowest first) nothing seems to happen

**Comment by e-maud** [comment]
In newspaper pages
About titles which are not there yet :
- [ ] greyed in the list (?)
- [ ] displaying ETA in the metadata

About first pages:
- [ ] thanks for previous fix, but some titles still show L'Impartial (GDL, Le Confédéré)

**Comment by mduering** [comment]
- [ ] interface accounts lists usernames as firstname.lastname but the login demands an email - (same problem as reported on slack before?) Lars could not log in this afternoon

**Comment by simon-clematide** [comment]
When ordering topic models by topic relevance, the top articles do not look as they would contain the relevant articles.  The screenshot of the topic 77fr (its probably a cycling/sports topic) shows that the most relevant articles have nothing to do with it.
Debugging from the interface is difficult if this view does not offer links to the article viewer (I cannot get to the article id of the shown articles; not even in HTML source). @danieleguido Could you somehow link to the article?)

![image](https://user-images.githubusercontent.com/3041168/53693192-64188880-3d9d-11e9-80bc-44f820d6888c.png)

**Comment by e-maud** [comment]
Topic page:
- [ ] search in topic raises an error

**Comment by simon-clematide** [comment]
CPU hog: Even when doing nothing in the article view, the page uses between 22-30% of my CPU on MacOS on Chrome.
![image](https://user-images.githubusercontent.com/3041168/53696860-7b6e6a80-3dcb-11e9-8dfd-4e0dbdca6d49.png)

**Comment by simon-clematide** [comment]
Overview over time should behave reasonably if a search hit can only be found in one year. There should be at least a decennium shown (e.g. in this case 1870-1880)
![image](https://user-images.githubusercontent.com/3041168/53696981-98576d80-3dcc-11e9-86e6-f8959b170102.png)

**Comment by simon-clematide** [comment]
The tiles view seems pretty idiosyncratic in terms of zooming in. I suggest to keep the zoom somewhat regularized. I know that we have the following cases:
 a. page articles (like NZZ) where 
 b. real articles currently without correct coordinates for articlese and search word
 c. real articles with correct coordinates for articles and search word
I suggest to horizontally zoom to  the line that contains the search word for case (c). 

![image](https://user-images.githubusercontent.com/3041168/53697037-46631780-3dcd-11e9-9a3f-716d17ca4cb4.png)

**Comment by simon-clematide** [comment]
The visualization of occurrences over years deals very badly with zero counts. In this example, the graph looks like there has been found 1 hit for all years from 1869 to 1980 with a few exceptions where 2 items have been found. Truth is, for many years there are zero hits, which are not visualized correctly.

![image](https://user-images.githubusercontent.com/3041168/53697146-9ee6e480-3dce-11e9-9ab9-5bfd2a87c33d.png)

**Comment by simon-clematide** [comment]
The article view for NZZ does not show any text for any page I tried.
![image](https://user-images.githubusercontent.com/3041168/53697233-aa86db00-3dcf-11e9-9a05-74b08d960271.png)

**Comment by danieleguido** [comment]
@simon-clematide many thanks for your feedbacks!! I'll resume them here

> The article view for NZZ does not show any text for any page I tried.
- [ ] Missing regions for NZZ in `rb_plain` field, check data coming from solr: `/solr/impresso/select?q=id:NZZ-1929-07-25-b-i0004` 

> The visualization of occurrences over years deals very badly with zero counts. In this example, the graph looks like there has been found 1 hit for all years from 1869 to 1980 with a few exceptions where 2 items have been found. Truth is, for many years there are zero hits, which are not visualized correctly.
- [ ] ref to issue #243

> The tiles view seems pretty idiosyncratic in terms of zooming in. I suggest to keep the zoom somewhat regularized. I know that we have the following cases:
a. page articles (like NZZ) where
b. real articles currently without correct coordinates for articlese and search word
c. real articles with correct coordinates for articles and search word
I suggest to horizontally zoom to the line that contains the search word for case (c).

- [ ] fix tiles view, next release? Ref to issue #244

> CPU hog: Even when doing nothing in the article view, the page uses between 22-30% of my CPU on MacOS on Chrome.
- [ ] fix perf leak in article view page (due to too many canvases?)

> Overview over time should behave reasonably if a search hit can only be found in one year. There should be at least a decennium shown (e.g. in this case 1870-1880)
(not sure I get it :) )

**Comment by Bunoute** [comment]
On the search page, some topics are "empty" on the left pane: only the number of articles are visible and no words
![image](https://user-images.githubusercontent.com/32094266/53738371-4fb4b880-3e8f-11e9-9286-a259230f806c.png)

**Comment by danieleguido** [comment]
@Bunoute which query did you perform? I cannot reproduce the bug

**Comment by Bunoute** [comment]
on the topic page for DE topics: the NZZ articles are not reachable: only the NZZ link, to the newspaper page of NZZ works, there is no title of the articles or other ways to go to the viewer
I tried with readable words and OCR fantasies:
https://impresso-project.ch/dev/#/topics/tmrero-de-alpha_tp25_de
https://impresso-project.ch/dev/#/topics/tmrero-de-alpha_tp46_de

**Comment by simon-clematide** [comment]
Some articles are shown twice, e.g. https://impresso-project.ch/dev/#/issue/LCR-1881-09-29-a/page/LCR-1881-09-29-a-p0003/article/LCR-1881-09-29-a-i0018.
 @danieleguido This is not the problem of the interface. But I still post it here so that it stays here as a known issue.
@mromanello  I checked the corresponding JSON file, and it contains the following:
```
{
  "id": "LCR-1881-09-29-a-i0018",
  "pp": [
    3,
    3
  ],
  "d": "1881-09-29",
  "olr": true,
  "ts": "2019-01-29T12:36:06Z",
  "lg": "fr",
  "tp": "ar",
...
```
I suspect the double entry of page 3 in attribute "pp" leads to the duplication in the interface.


![image](https://user-images.githubusercontent.com/3041168/53746340-43d1f200-3ea1-11e9-8c81-4f83733c6fc3.png)

**Comment by simon-clematide** [comment]
Inform the user (transparency) that no topic model has been computed for this article. No just showing nothing. Maybe something like: "This article is not indexed by our topic model."

![image](https://user-images.githubusercontent.com/3041168/53807542-2445d280-3f50-11e9-8a4e-fb15fb2a6a94.png)

**Comment by simon-clematide** [comment]
Hyphenated words at region boundaries are not accurately rendered in text form (see red rectangles in screenshot).
@mromanello Not sure whether this comes from our side.

https://impresso-project.ch/dev/#/issue/IMP-1894-07-05-a/page/IMP-1894-07-05-a-p0004/article/IMP-1894-07-05-a-i0036

![image](https://user-images.githubusercontent.com/3041168/53820275-b9a29000-3f6b-11e9-9847-c0ade38f4899.png)

**Comment by simon-clematide** [comment]
Some images do not loaded from IIIF because they reference boundary boxes outside the image size.
@e-maud @mromanello we should make sure that all boundary boxes stay within the reference image size. 
See article https://impresso-project.ch/dev/#/issue/EXP-1902-04-16-a/page/EXP-1902-04-16-a-p0004/article/EXP-1902-04-16-a-i0052 
that reference the following region:

https://impresso-project.ch/alpha/api/proxy/iiif/EXP-1902-04-16-a-p0004/14,2320,356,2869/full/0/default.png

**Comment by simon-clematide** [comment]
> @simon-clematide many thanks for your feedbacks!! I'll resume them here
> 
> > The article view for NZZ does not show any text for any page I tried.
> 
> * [ ]  Missing regions for NZZ in `rb_plain` field, check data coming from solr: `/solr/impresso/select?q=id:NZZ-1929-07-25-b-i0004`


@danieleguido  Is this now a backend problem or a frontend problem? Would be helpful to be able to look at German material.
